name: Auto Deploy to Netlify

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  auto-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install necessary packages
        run: npm install
      - name: Testing the project
        run: cd Server && npm install && npm run test
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          PORT: 3001
          DB_URL: "mongodb+srv://himmatramka2003:naman123@cluster0.z4alohf.mongodb.net/test"
          SECRET_KEY: "test-secret"
          EMAIL_USER: naman.himmatramka@spit.ac.in
      - name: Build the project
        run: CI=false npm run build
      - name: Publish
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=out